### ISSUE TITLE
Bad characters in label

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#10]
If you want to create or modify a project so that in the label it contains forbidden characters (that should be escaped) a weird error occurs:

```
PASSED                       [100%]{'message': 'GraphDB Transaction update failed. Reason: "Transaction handling error: Lexical error at line 20, column 33.  Encountered: \'43\' (43), after prefix "usw""'}
```
I suspect that the same problem happens with the comment and other LangString instances as well

**Comment by ManuelRosenthaler** [comment]
EDIT: Confirmation of my suspicion. When i try to create a project with the entry `"gaga\"usw++@en"` in the comment part, i receve the same error

```
PASSED                       [100%]{'message': 'GraphDB Transaction update failed. Reason: "Transaction handling error: Lexical error at line 21, column 35.  Encountered: \'43\' (43), after prefix "usw""'}
```

**Comment by lrosenth** [comment]
Fixed. Will be part of next pypi release!
