### ISSUE TITLE
Giving None in xsd_date does not work

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#13]
Giving None in an xsd_date should give the current day as xsd_date given that the xsd_date is used as the startdate. However, it does not seem that giving a None to an xsd_date is catched in the constructer of the xsd_date

-> Make it possible to give None as parameter in a xsd_date

**Comment by lrosenth** [comment]
If an Xsd_date is created with nore parameter or None, the current date is used.
