### ISSUE TITLE
Modify xsd_ENDdate so that it is BEFORE the startdate

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#15]
It seems that there is no error raised, when you modify the enddate to be BEFORE the startdate during the project.update. That leads to some very weird errors...

When i have a project with the startdate 1993-04-05 and the enddate 2024-04-05 but then i modify the enddate to be 1992-04-05 the update routine does not seem to check if the enddate is a valid one (i dont see that a inconsistency error is raised...) which in turn leads to very severe problems (code crashes as it seems...)

**Comment by lrosenth** [comment]
Fixed and tested
