### ISSUE TITLE
Question: How should the API react if there is nonsense in the JSON?

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#18]
Lets assume a person creates a project as follows:

```
    response = client.put('/admin/project/testproject', json={
        "kappa": "",
        "projectIri": "http://unittest.org/project/testproject",
        "label": ["unittest@en", "unittest@de"],
        "comment": ["For testing@en", "Für Tests@de"],
        "namespaceIri": "http://unitest.org/project/unittest#",
        "projectStart": "1993-04-05",
        "projectEnd": "2000-01-10"
    }, headers=header)
```

As you can see, the first entry is nonsense... Should the API
1. abord the creation and tell the user that one field is not supported?
2. create the project but inform the user that one of the fields was not supportet?
3. create the project and just ignore the nonsensicle entry?

The same question stans when a user wants to **modify** a nonexisting entry in a project... the question is the same: Should the API
1. abord the modify and tell the user that one field is not supported?
2. modify the project but inform the user that one of the fields was not supportet?
3. modify the project and just ignore the nonsensicle entry?

**Comment by lrosenth** [comment]
I think invalid JSON in the sense that a known/undefined field appears should abort with an error message and do nothing. In the example above the command should abort. What do You think?

**Comment by ManuelRosenthaler** [comment]
Is implemented that the whole operations abords when there is something unknown in the json
