### ISSUE TITLE
Error message when xsd_date is not well formed

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#2]
The error message you receive, when you give a xsd_date that is badly formed is not that good. Instead of writing "8.9.1993 wrong format for xsd:date." its better to tell the user how an xsd_date IS well formed e.g. "8.9.1993 wrong format for xsd:date. - right format is yyyy-mm-dd". Probably change that

**Comment by lrosenth** [comment]
Error message improved.
