### ISSUE TITLE
Empty comment in project?

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#4]
Should it be allowed to create a project that has an empty comment? In order to create a project, i expect that at least the projectshortname, label, comment and namespaceIri are required. But you can just simply enter an empty comment which has the same effect as to create a project without a comment. is that intendet? 

```Python
    response = client.put('/admin/project/testproject', json={
        "projectIri": "http://unittest.org/project/testproject",
        "label": ["unittest@en", "unittest@de"],
        "comment": [],
        "namespaceIri": "http://unitest.org/project/unittest#",
        "projectStart": "1993-04-05",
        "projectEnd": "2000-01-10"
    }, headers=header)
```

**Comment by lrosenth** [comment]
A ProjectClass may *not* have an empty label. If this is the case, now a "OmasErrorInconsistency" is raised.
However a ProjectClass may have no comment. Empty comment parameters as „LangString()“ or „LangString([])“ are allowed and are considered to be None (e.g. no comment).
