### ISSUE TITLE
Missing error raise in LangString

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/omaslib#5]
When you enter a integer into a LangString, no error is raised and the programm "crashes". --> Need to throw an error for the case when an integer is entered for a langstring

```
(...)
E               TypeError: 'int' object is not subscriptable

../../../Library/Caches/pypoetry/virtualenvs/oldap-api-rl24mTKu-py3.12/lib/python3.12/site-packages/omaslib/src/helpers/langstring.py:110: TypeError
```

**Comment by ManuelRosenthaler** [comment]
Just as a sidenote: A similar problem arises when you give a simple string to a LangString(). The error handling is working yet a bit cryptic... if i give a LansString() a simple string i recieve the error message:

```
PASSED                               [100%]{'message': 'GraphDB Transaction update failed. Reason: "Transaction handling error: Lexical error at line 21, column 31.  Encountered: \'32\' (32), after prefix "For""'}
```
Maybe something more understandable would be good

**Comment by lrosenth** [comment]
Problem fixed.
